version: '3.8'
services:
hls-server:
build: ./hls-server
volumes:
- ./hls-server/hls-output:/var/www/hls
ports:
- 8080:80
restart: unless-stopped


sync-server:
build: ./sync-server
working_dir: /app
command: node index.js
ports:
- 3001:3001
depends_on:
- hls-server
restart: unless-stopped


client:
build: ./client
ports:
- 3000:3000
depends_on:
- sync-server
restart: unless-stopped